name: CI

# Trigger the workflow on pull requests to the main branch
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: void_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.15.7'
        otp-version: '26'

    - name: Install dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get

    - name: Set up the database
      run:  | 
        mix ecto.setup
        mix ecto.create
        mix ecto.migrate
        mix run priv/repo/seeds.exs  

    - name: Run Elixir tests
      run: mix test
      env:
        MIX_ENV: test
        DATABASE_URL: ecto://postgres:postgres@localhost/void_test

    - name: Run the Phoenix server in the background
      run: |
        mix phx.server &
        sleep 5
        until curl -sSf http://localhost:4002 > /dev/null; do
          printf '.'
          sleep 5
        done
      env:
        MIX_ENV: test
        DATABASE_URL: ecto://postgres:postgres@localhost/void_test

    - name: Run Playwright tests
      run: |
        docker run --rm \
          -v $PWD:/app \
          -w /app/test/pw \
          mcr.microsoft.com/playwright:v1.46.1-jammy \
          sh -c "yarn install;yarn test"
